// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteAllEndpoints = `-- name: DeleteAllEndpoints :exec
DELETE FROM webhook_endpoints
`

func (q *Queries) DeleteAllEndpoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEndpoints)
	return err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT
  (SELECT COUNT(*) FROM users) AS users,
  (SELECT COUNT(*) FROM webhook_events) AS events_received,
  (SELECT COUNT(*) FROM deliveries WHERE status = 'success') AS successful_deliveries,
  (SELECT COUNT(*) FROM deliveries WHERE status = 'failed') AS failed_deliveries,
  (SELECT COUNT(*) FROM deliveries WHERE status = 'retry_scheduled') AS retry_scheduled_deliveries
`

type GetAdminStatsRow struct {
	Users                    int64
	EventsReceived           int64
	SuccessfulDeliveries     int64
	FailedDeliveries         int64
	RetryScheduledDeliveries int64
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.Users,
		&i.EventsReceived,
		&i.SuccessfulDeliveries,
		&i.FailedDeliveries,
		&i.RetryScheduledDeliveries,
	)
	return i, err
}

const getAllDeliveries = `-- name: GetAllDeliveries :many
SELECT
  d.created_at,
  d.status,
  d.status_code,
  ep.name AS endpoint_name,
  u.name AS user_name
FROM deliveries d
JOIN webhook_events e
  ON e.id = d.event_id
JOIN webhook_endpoints ep
  ON ep.id = e.endpoint_id
JOIN users u
  ON u.id = ep.user_id
ORDER BY d.created_at DESC
LIMIT 10
`

type GetAllDeliveriesRow struct {
	CreatedAt    time.Time
	Status       string
	StatusCode   sql.NullInt32
	EndpointName string
	UserName     string
}

func (q *Queries) GetAllDeliveries(ctx context.Context) ([]GetAllDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDeliveriesRow
	for rows.Next() {
		var i GetAllDeliveriesRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Status,
			&i.StatusCode,
			&i.EndpointName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEndpoints = `-- name: GetAllEndpoints :many
SELECT 
  ep.name, 
  ep.is_active, 
  ep.created_at, 
  ep.user_id,
  u.name as user_name
FROM webhook_endpoints ep
JOIN users u
  ON u.id = ep.user_id
ORDER BY ep.created_at DESC
LIMIT 10
`

type GetAllEndpointsRow struct {
	Name      string
	IsActive  bool
	CreatedAt time.Time
	UserID    uuid.NullUUID
	UserName  string
}

func (q *Queries) GetAllEndpoints(ctx context.Context) ([]GetAllEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEndpointsRow
	for rows.Next() {
		var i GetAllEndpointsRow
		if err := rows.Scan(
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT
  e.received_at,
  e.event_type,
  ep.name AS endpoint_name,
  u.name AS user_name
FROM webhook_events e
JOIN webhook_endpoints ep
  ON ep.id = e.endpoint_id
JOIN users u
  ON u.id = ep.user_id
ORDER BY e.received_at DESC
LIMIT 10
`

type GetAllEventsRow struct {
	ReceivedAt   time.Time
	EventType    sql.NullString
	EndpointName string
	UserName     string
}

func (q *Queries) GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(
			&i.ReceivedAt,
			&i.EventType,
			&i.EndpointName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT 
  id, 
  name, 
  email, 
  created_at, 
  updated_at, 
  is_admin 
FROM users
`

type GetAllUsersRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsAdmin   bool
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT
  e.id AS event_id,
  e.received_at,
  ep.name AS endpoint_name,
  u.name AS user_name,
  e.event_type,
  COALESCE(d.status, 'pending') AS latest_delivery_status,
  d.status_code AS latest_delivery_status_code
FROM webhook_events e
JOIN webhook_endpoints ep
  ON ep.id = e.endpoint_id
JOIN users u
  ON u.id = ep.user_id
LEFT JOIN LATERAL (
  SELECT
    status,
    status_code,
    created_at
  FROM deliveries
  WHERE deliveries.event_id = e.id
  ORDER BY created_at DESC
  LIMIT 1
) d ON true
ORDER BY e.received_at DESC
LIMIT 10
`

type GetRecentActivityRow struct {
	EventID                  uuid.UUID
	ReceivedAt               time.Time
	EndpointName             string
	UserName                 string
	EventType                sql.NullString
	LatestDeliveryStatus     string
	LatestDeliveryStatusCode sql.NullInt32
}

func (q *Queries) GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.EventID,
			&i.ReceivedAt,
			&i.EndpointName,
			&i.UserName,
			&i.EventType,
			&i.LatestDeliveryStatus,
			&i.LatestDeliveryStatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
