// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
)

const getAdminStats = `-- name: GetAdminStats :one
SELECT
  (SELECT COUNT(*) FROM users) AS users,
  (SELECT COUNT(*) FROM webhook_events) AS events_received,
  (SELECT COUNT(*) FROM deliveries WHERE status = 'success') AS successful_deliveries,
  (SELECT COUNT(*) FROM deliveries WHERE status = 'failed') AS failed_deliveries
`

type GetAdminStatsRow struct {
	Users                int64
	EventsReceived       int64
	SuccessfulDeliveries int64
	FailedDeliveries     int64
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.Users,
		&i.EventsReceived,
		&i.SuccessfulDeliveries,
		&i.FailedDeliveries,
	)
	return i, err
}
