// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
    event_id,
    target_url,
    status,
    status_code,
    response_body,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, event_id, target_url, status, status_code, response_body, error_message, created_at, attempted_at, delivered_at, attempt_count, next_retry_at, delivery_duration_ms
`

type CreateDeliveryParams struct {
	EventID      uuid.UUID
	TargetUrl    string
	Status       string
	StatusCode   sql.NullInt32
	ResponseBody sql.NullString
	ErrorMessage sql.NullString
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, createDelivery,
		arg.EventID,
		arg.TargetUrl,
		arg.Status,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TargetUrl,
		&i.Status,
		&i.StatusCode,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.AttemptedAt,
		&i.DeliveredAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.DeliveryDurationMs,
	)
	return i, err
}
