// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
    event_id,
    target_url,
    status,
    status_code,
    response_body,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, event_id, target_url, status, status_code, response_body, error_message, created_at, attempted_at, delivered_at, attempt_count, next_retry_at, delivery_duration_ms
`

type CreateDeliveryParams struct {
	EventID      uuid.UUID
	TargetUrl    string
	Status       string
	StatusCode   sql.NullInt32
	ResponseBody sql.NullString
	ErrorMessage sql.NullString
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, createDelivery,
		arg.EventID,
		arg.TargetUrl,
		arg.Status,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TargetUrl,
		&i.Status,
		&i.StatusCode,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.AttemptedAt,
		&i.DeliveredAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.DeliveryDurationMs,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT 
    deliveries.id,
    webhook_endpoints.name AS endpoint_name,
    deliveries.target_url,
    deliveries.status,
    deliveries.status_code,
    deliveries.created_at,
    deliveries.delivery_duration_ms
FROM deliveries
JOIN webhook_events ON deliveries.event_id = webhook_events.id
JOIN webhook_endpoints ON webhook_events.endpoint_id = webhook_endpoints.id
ORDER BY deliveries.created_at DESC
`

type ListDeliveriesRow struct {
	ID                 uuid.UUID
	EndpointName       string
	TargetUrl          string
	Status             string
	StatusCode         sql.NullInt32
	CreatedAt          time.Time
	DeliveryDurationMs sql.NullInt32
}

func (q *Queries) ListDeliveries(ctx context.Context) ([]ListDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveriesRow
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointName,
			&i.TargetUrl,
			&i.Status,
			&i.StatusCode,
			&i.CreatedAt,
			&i.DeliveryDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :exec
UPDATE deliveries
SET 
    status = $2,
    status_code = $3,
    response_body = $4,
    error_message = $5,
    delivery_duration_ms = $6,
    attempted_at = NOW(),
    attempt_count = attempt_count + 1,
    delivered_at = CASE
        WHEN $2 = 'success' THEN NOW()
        ELSE delivered_at
END
WHERE id = $1
`

type UpdateDeliveryParams struct {
	ID                 uuid.UUID
	Status             string
	StatusCode         sql.NullInt32
	ResponseBody       sql.NullString
	ErrorMessage       sql.NullString
	DeliveryDurationMs sql.NullInt32
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, updateDelivery,
		arg.ID,
		arg.Status,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.DeliveryDurationMs,
	)
	return err
}
