// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package database

import (
	"context"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO webhook_endpoints (name, target_url)
VALUES ($1, $2)
RETURNING id, name, target_url, is_active, created_at, updated_at
`

type CreateEndpointParams struct {
	Name      string
	TargetUrl string
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, createEndpoint, arg.Name, arg.TargetUrl)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
