// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO webhook_endpoints (name, target_url, description, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, target_url, is_active, created_at, updated_at, description, user_id
`

type CreateEndpointParams struct {
	Name        string
	TargetUrl   string
	Description sql.NullString
	UserID      uuid.NullUUID
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, createEndpoint,
		arg.Name,
		arg.TargetUrl,
		arg.Description,
		arg.UserID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const deleteAllEndpoints = `-- name: DeleteAllEndpoints :exec
DELETE FROM webhook_endpoints
`

func (q *Queries) DeleteAllEndpoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEndpoints)
	return err
}

const deleteEndpointByID = `-- name: DeleteEndpointByID :exec
DELETE FROM webhook_endpoints
WHERE id = $1
`

func (q *Queries) DeleteEndpointByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEndpointByID, id)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, name, target_url, is_active, created_at, updated_at, description, user_id FROM webhook_endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, name, target_url, is_active, created_at, updated_at, description, user_id FROM webhook_endpoints
ORDER BY created_at DESC
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE webhook_endpoints
SET name = $2, target_url = $3, description = $4
WHERE id = $1
RETURNING id, name, target_url, is_active, created_at, updated_at, description, user_id
`

type UpdateEndpointParams struct {
	ID          uuid.UUID
	Name        string
	TargetUrl   string
	Description sql.NullString
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpoint,
		arg.ID,
		arg.Name,
		arg.TargetUrl,
		arg.Description,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.UserID,
	)
	return i, err
}
