// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO webhook_events(endpoint_id, event_type, payload, headers) 
VALUES ($1, $2, $3, $4) 
RETURNING id, endpoint_id, event_type, payload, headers, received_at
`

type CreateEventParams struct {
	EndpointID uuid.UUID
	EventType  string
	Payload    json.RawMessage
	Headers    json.RawMessage
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (WebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.EndpointID,
		arg.EventType,
		arg.Payload,
		arg.Headers,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Headers,
		&i.ReceivedAt,
	)
	return i, err
}
