// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Delivery struct {
	ID                 uuid.UUID
	EventID            uuid.UUID
	TargetUrl          string
	Status             string
	StatusCode         sql.NullInt32
	ResponseBody       sql.NullString
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
	AttemptedAt        sql.NullTime
	DeliveredAt        sql.NullTime
	AttemptCount       int32
	NextRetryAt        sql.NullTime
	DeliveryDurationMs sql.NullInt32
}

type User struct {
	ID             uuid.UUID
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsAdmin        bool
}

type WebhookEndpoint struct {
	ID          uuid.UUID
	Name        string
	TargetUrl   string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	UserID      uuid.NullUUID
}

type WebhookEvent struct {
	ID         uuid.UUID
	EndpointID uuid.UUID
	EventType  sql.NullString
	Payload    json.RawMessage
	Headers    json.RawMessage
	ReceivedAt time.Time
}
