// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Delivery struct {
	ID                 uuid.UUID
	EventID            uuid.UUID
	TargetUrl          string
	Status             string
	StatusCode         sql.NullInt32
	ResponseBody       sql.NullString
	ErrorMessage       sql.NullString
	CreatedAt          time.Time
	AttemptedAt        sql.NullTime
	DeliveredAt        sql.NullTime
	AttemptCount       int32
	NextRetryAt        sql.NullTime
	DeliveryDurationMs sql.NullInt32
}

type WebhookEndpoint struct {
	ID        uuid.UUID
	Name      string
	TargetUrl string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
