// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, email, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, name, email, hashed_password, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	Name           string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE is_admin = false
AND id = $1
RETURNING id
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, hashed_password, created_at, updated_at, is_admin FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserRecentActvity = `-- name: GetUserRecentActvity :many
SELECT
    e.id AS event_id,
    e.received_at,
    e.event_type,
    ep.name AS endpoint_name,
    COALESCE(d.status, 'pending') AS latest_delivery_status,
    d.status_code AS latest_delivery_status_code,
    COALESCE(d.attempt_count, 0) AS attempt_count,
    d.id AS delivery_id
FROM webhook_events e
JOIN webhook_endpoints ep
    ON ep.id = e.endpoint_id
LEFT JOIN LATERAL (
    SELECT
        status,
        status_code,
        created_at,
        attempt_count,
        id
    FROM deliveries
    WHERE deliveries.event_id = e.id
    ORDER BY created_at DESC
    LIMIT 1
) d ON true
WHERE ep.user_id = $1
ORDER BY e.received_at DESC
LIMIT 10
`

type GetUserRecentActvityRow struct {
	EventID                  uuid.UUID
	ReceivedAt               time.Time
	EventType                sql.NullString
	EndpointName             string
	LatestDeliveryStatus     string
	LatestDeliveryStatusCode sql.NullInt32
	AttemptCount             int32
	DeliveryID               uuid.UUID
}

func (q *Queries) GetUserRecentActvity(ctx context.Context, userID uuid.NullUUID) ([]GetUserRecentActvityRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecentActvity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentActvityRow
	for rows.Next() {
		var i GetUserRecentActvityRow
		if err := rows.Scan(
			&i.EventID,
			&i.ReceivedAt,
			&i.EventType,
			&i.EndpointName,
			&i.LatestDeliveryStatus,
			&i.LatestDeliveryStatusCode,
			&i.AttemptCount,
			&i.DeliveryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatsByID = `-- name: GetUserStatsByID :one
SELECT
    COUNT(DISTINCT ep.id) AS endpoint_count,
    COUNT(DISTINCT e.id) AS event_count,
    COUNT(DISTINCT CASE WHEN d.status = 'success' THEN d.id END) AS successful_delivery_count,
    COUNT(DISTINCT CASE WHEN d.status = 'dead_letter' THEN d.id END) AS failed_delivery_count,
    COUNT(DISTINCT CASE WHEN d.status = 'retry_scheduled' THEN d.id END) AS retry_scheduled_delivery_count
FROM webhook_endpoints ep
LEFT JOIN webhook_events e ON ep.id = e.endpoint_id
LEFT JOIN deliveries d ON e.id = d.event_id
WHERE ep.user_id = $1
`

type GetUserStatsByIDRow struct {
	EndpointCount               int64
	EventCount                  int64
	SuccessfulDeliveryCount     int64
	FailedDeliveryCount         int64
	RetryScheduledDeliveryCount int64
}

func (q *Queries) GetUserStatsByID(ctx context.Context, userID uuid.NullUUID) (GetUserStatsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserStatsByID, userID)
	var i GetUserStatsByIDRow
	err := row.Scan(
		&i.EndpointCount,
		&i.EventCount,
		&i.SuccessfulDeliveryCount,
		&i.FailedDeliveryCount,
		&i.RetryScheduledDeliveryCount,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT is_admin FROM users WHERE id = $1
`

func (q *Queries) IsUserAdmin(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}
